name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Notebook to markdown
      run: |
        pip install nbconvert
        jupyter nbconvert --to markdown mcst.ipynb
    - name: Markdown to readme
      run: |
        mv mcst.md README.md
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "chore: update readme"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
